server:
  port: 8080
spring:
  datasource:
    url: ${SQL_URI:jdbc:postgresql://localhost:5432/postgres?currentSchema=hibernate_tutorial}
    username: ${SQL_USER:admin}
    password: ${SQL_PASSWORD:123456}

  jpa:
    hibernate:
      ddl-auto: update
